### ISSUE TITLE
InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero

### ISSUE THREAD

**Issue by Jeiyoon** [v-iashin/video_features#20]
Hi

Thank you for your great works in advance

I've encountered a problem:

~~~
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[{{node vggish/Flatten/flatten/Reshape}}]]
	 [[{{node vggish/embedding}}]]
~~~

Some video datasets are fine but this problem occurs often :(

Here's my full logs:

~~~
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

  0%|                                                     | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[{{node vggish/Flatten/flatten/Reshape}}]]
	 [[{{node vggish/embedding}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/extract_vggish.py", line 60, in forward
    self.extract(idx, sess)
  File "/data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/extract_vggish.py", line 97, in extract
    [vggish_stack] = tf_session.run([embedding_tensor], feed_dict={features_tensor: examples_batch})
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[node vggish/Flatten/flatten/Reshape (defined at /data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py:95) ]]
	 [[node vggish/embedding (defined at /data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py:99) ]]

Caused by op 'vggish/Flatten/flatten/Reshape', defined at:
  File "/data02/jeiyoon_park/BMT/submodules/video_features/main.py", line 85, in <module>
    parallel_feature_extraction(args)
  File "/data02/jeiyoon_park/BMT/submodules/video_features/main.py", line 34, in parallel_feature_extraction
    torch.nn.parallel.parallel_apply(replicas[:len(inputs)], inputs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 79, in parallel_apply
    _worker(0, modules[0], inputs[0], kwargs_tup[0], devices[0])
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/extract_vggish.py", line 52, in forward
    vggish_slim.define_vggish_slim(training=False)
  File "/data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py", line 95, in define_vggish_slim
    net = slim.flatten(net)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1624, in flatten
    outputs = core_layers.flatten(inputs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/layers/core.py", line 333, in flatten
    return layer.apply(inputs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py", line 553, in call
    array_ops.shape(inputs)[0], -1))
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[node vggish/Flatten/flatten/Reshape (defined at /data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py:95) ]]
	 [[node vggish/embedding (defined at /data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py:99) ]]

Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[node vggish/Flatten/flatten/Reshape (defined at /data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py:95) ]]
	 [[node vggish/embedding (defined at /data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py:99) ]]

Caused by op 'vggish/Flatten/flatten/Reshape', defined at:
  File "/data02/jeiyoon_park/BMT/submodules/video_features/main.py", line 85, in <module>
    parallel_feature_extraction(args)
  File "/data02/jeiyoon_park/BMT/submodules/video_features/main.py", line 34, in parallel_feature_extraction
    torch.nn.parallel.parallel_apply(replicas[:len(inputs)], inputs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 79, in parallel_apply
    _worker(0, modules[0], inputs[0], kwargs_tup[0], devices[0])
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/extract_vggish.py", line 52, in forward
    vggish_slim.define_vggish_slim(training=False)
  File "/data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py", line 95, in define_vggish_slim
    net = slim.flatten(net)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1624, in flatten
    outputs = core_layers.flatten(inputs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/layers/core.py", line 333, in flatten
    return layer.apply(inputs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py", line 553, in call
    array_ops.shape(inputs)[0], -1))
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/data02/jeiyoon_park/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[node vggish/Flatten/flatten/Reshape (defined at /data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py:95) ]]
	 [[node vggish/embedding (defined at /data02/jeiyoon_park/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py:99) ]]

Extraction failed at: /data02/jeiyoon_park/fairseq/examples/MMPT/video_dataset/SumMe/SumMe/pasted_videos/Bearpark_climbing.mp4. Continuing extraction
100%|█████████████████████████████████████████████| 1/1 [00:04<00:00,  4.68s/it]

Process finished with exit code 0
~~~

**Comment by v-iashin** [comment]
Hi,

Thanks for making an issue.

Can you make a minimal working example (e.g. Google Colab) and provide the videos that you are trying to use (one video where the model works, one where it does not)? 

Also, which branch are you using? On the `main` branch, vggish is implemented with PyTorch but your trackback seems to be from Tensorflow.

**Comment by Jeiyoon** [comment]
You mean this minimal example?:

https://colab.research.google.com/github/v-iashin/BMT/blob/master/colab_demo_BMT.ipynb#scrollTo=GanvtYi41tc1


I'm using your great work BMT 

https://github.com/v-iashin/BMT

, and this model needs I3D and Vggish features so I'm also using works

https://github.com/v-iashin/video_features/tree/4fa02bd5c5b8c34081dcfb609e2bcd5a973eaab2

Can i use another code which is implemented with PyTorch?

**Comment by v-iashin** [comment]
> You mean this minimal example?:

I think this Colab works. Can you share a video with which it does not work? To save time (this Google Colab it slow), you can use the https://github.com/v-iashin/video_features/tree/4fa02bd5c5b8c34081dcfb609e2bcd5a973eaab2 branch to extract features for vggish specifically and debug the code.

> Can i use another code which is implemented with PyTorch?

Well, if you just need VGGish features, you may switch to `video_features/main` and use this [Colab for feature extraction](https://colab.research.google.com/drive/1r_8OnmwXKwmH0n4RxBfuICVBgpbJt_Fs?usp=sharing).

However, if you would like to you BMT, then this suggestion won't help.

**Comment by Jeiyoon** [comment]
I ran your colab code and i encountered same issue below while extracting vggish features:

~~~
Saving features to /content/BMT/tmp/
100% 1/1 [01:31<00:00, 91.19s/it]
Saving features to /content/BMT/tmp/

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

  0% 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/BMT/submodules/video_features/models/vggish/extract_vggish.py", line 60, in forward
    self.extract(idx, sess)
  File "/content/BMT/submodules/video_features/models/vggish/extract_vggish.py", line 94, in extract
    examples_batch = vggish_input.wavfile_to_examples(audio_wav_path)
  File "/content/BMT/submodules/video_features/models/vggish/vggish_src/vggish_input.py", line 84, in wavfile_to_examples
    wav_data, sr = sf.read(wav_file, dtype='int16')
  File "/usr/local/envs/vggish/lib/python3.7/site-packages/soundfile.py", line 373, in read
    subtype, endian, format, closefd) as f:
  File "/usr/local/envs/vggish/lib/python3.7/site-packages/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/envs/vggish/lib/python3.7/site-packages/soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/local/envs/vggish/lib/python3.7/site-packages/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening './tmp/Bearpark_climbing.wav': System error.
Error opening './tmp/Bearpark_climbing.wav': System error.
Extraction failed at: /content/drive/MyDrive/SumMe/SumMe/videos/Bearpark_climbing.mp4. Continuing extraction
100% 1/1 [00:03<00:00,  3.73s/it]
~~~

**Comment by Jeiyoon** [comment]
I also ran this [colab code](https://colab.research.google.com/drive/1r_8OnmwXKwmH0n4RxBfuICVBgpbJt_Fs?usp=sharing)  and same issue occurred...


<img width="445" alt="Capture" src="https://user-images.githubusercontent.com/56618962/168503368-bb86e6e0-c69d-4370-a1fd-19cf8a870dd5.PNG">

**Comment by Jeiyoon** [comment]
Problem solved!

I edit your code and it works without errors

'''python
# load pretrained model: vggish
model = torch.hub.load('harritaylor/torchvggish', 'vggish')
model.eval()

def parallel_feature_extraction(args, video_path):
# def parallel_feature_extraction(args):
    '''Distributes the feature extraction in a embarasingly-parallel fashion. Specifically,
    it divides the dataset (list of video paths) among all specified devices evenly.'''

    if args.feature_type == 'i3d':
        from models.i3d.extract_i3d import ExtractI3D  # defined here to avoid import errors
        args.video_paths = video_path # editted
        extractor = ExtractI3D(args)
    elif args.feature_type == 'vggish':
        # mp4 to wav
        input_path = str(video_path[0])
        output_path = input_path.replace('mp4', 'wav')
        clip = mp.VideoFileClip(input_path)
        clip.audio.write_audiofile(output_path)

        # vggish.npy save
        vggish_save_dir = '/data02/jeiyoon_park/fairseq/examples/MMPT/i3d_features/SumMe/'
        vggish_result = model.forward(output_path)
        np.save(str(vggish_save_dir + input_path.split('/')[-1].replace('mp4', 'npy')), vggish_result.detach().cpu())
'''

**Comment by Jeiyoon** [comment]
I've compared both vggish from your code and mine, and it looks different...

<img width="862" alt="Capture" src="https://user-images.githubusercontent.com/56618962/168516446-e7dd88c1-c8c2-4e32-a12d-f0c5301a8a2a.PNG">

**Comment by v-iashin** [comment]
There are two problems that I see from this screenshot you shared.

1. The features are quantized (8-bit). I assume you post-process your features. Check out what the other implementation that you are using now outputs: [intuition](https://github.com/tensorflow/models/tree/master/research/audioset/vggish#output-embeddings) and [the code](https://github.com/tensorflow/models/blob/master/research/audioset/vggish/vggish_postprocess.py). In this repo, we do not use the quantization and the rest of post-processing: 
https://github.com/v-iashin/video_features/blob/3ca0b62a274e6eab7518ead2db919674e99b1989/models/vggish/vggish_src/vggish_slim.py#L95-L99

2. The size mismatch. Here I don't know what exactly is happening. It can be either difference in sampling rate, spectrogram extraction hyper-parameters, or something else. Make sure, you are not skipping the pre-processing step where the audio is resampled
https://github.com/v-iashin/video_features/blob/3ca0b62a274e6eab7518ead2db919674e99b1989/models/vggish/vggish_src/vggish_slim.py#L151-L152

**Comment by Jeiyoon** [comment]
> There are two problems that I see from this screenshot you shared.
> 
> 1. The features are quantized (8-bit). I assume you post-process your features. Check out what the other implementation that you are using now outputs: [intuition](https://github.com/tensorflow/models/tree/master/research/audioset/vggish#output-embeddings) and [the code](https://github.com/tensorflow/models/blob/master/research/audioset/vggish/vggish_postprocess.py). In this repo, we do not use the quantization and the rest of post-processing:
>    https://github.com/v-iashin/video_features/blob/3ca0b62a274e6eab7518ead2db919674e99b1989/models/vggish/vggish_src/vggish_slim.py#L95-L99
> 2. The size mismatch. Here I don't know what exactly is happening. It can be either difference in sampling rate, spectrogram extraction hyper-parameters, or something else. Make sure, you are not skipping the pre-processing step where the audio is resampled
>    https://github.com/v-iashin/video_features/blob/3ca0b62a274e6eab7518ead2db919674e99b1989/models/vggish/vggish_src/vggish_slim.py#L151-L152

Problem has been solved!

Most videos are fine but a dataset

I found your code convert mp4 to "aac" and then to "wav"

This converting process didn't work well on the dataset. 

So I fixed some code about generating wav file, using "moviepy" library and your code is working well on the dataset


I really appreciate your effort!!! 😆😆😆
